# This file tells GitHub Pages what to do.
# By leaving this blank, we let our custom index.html file take control.
 
# Site settings
title: TJJZ's Portfolio
description: My personal engineering portfoli
